// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXRXCWN-37cZkag0mxgpGvJrdETssv0Ow',
    appId: '1:929266846604:web:b85e53647a5ec4fefb24a9',
    messagingSenderId: '929266846604',
    projectId: 'chatapp-be83f',
    authDomain: 'chatapp-be83f.firebaseapp.com',
    storageBucket: 'chatapp-be83f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUD8H9IYx5M7yvycUzUsNAXrb3RujfcVI',
    appId: '1:929266846604:android:ac041efb8f9b138cfb24a9',
    messagingSenderId: '929266846604',
    projectId: 'chatapp-be83f',
    storageBucket: 'chatapp-be83f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjetMlh0V47tQPKeR4oPnVJoEa0CyWuXA',
    appId: '1:929266846604:ios:b4547b22153fe47efb24a9',
    messagingSenderId: '929266846604',
    projectId: 'chatapp-be83f',
    storageBucket: 'chatapp-be83f.firebasestorage.app',
    iosBundleId: 'com.example.chapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjetMlh0V47tQPKeR4oPnVJoEa0CyWuXA',
    appId: '1:929266846604:ios:b4547b22153fe47efb24a9',
    messagingSenderId: '929266846604',
    projectId: 'chatapp-be83f',
    storageBucket: 'chatapp-be83f.firebasestorage.app',
    iosBundleId: 'com.example.chapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXRXCWN-37cZkag0mxgpGvJrdETssv0Ow',
    appId: '1:929266846604:web:08fdadf3b8665545fb24a9',
    messagingSenderId: '929266846604',
    projectId: 'chatapp-be83f',
    authDomain: 'chatapp-be83f.firebaseapp.com',
    storageBucket: 'chatapp-be83f.firebasestorage.app',
  );

}